version: '3.4'
services:
  ########################
  # SERVICE DEPENDENCIES #
  ########################
  mariadb:
    image: mariadb:10.3.10
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=productzilla
      - MYSQL_DATABASE=productzilla
      - MYSQL_USER=productzilla
      - MYSQL_PASSWORD=productzilla
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '--silent']
      start_period: 30s
    ports:
      - 31360:3306
    networks:
      default:
    volumes:
      - ./volumes/mariadb:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    restart: unless-stopped
    ports:
      - 31361:80
    environment:
      - PMA_HOST=mariadb
      - UPLOAD_LIMIT=100M
  
  proxy:
    image: dannydirect/tinyproxy:latest
    ports:
      - 8882:8888
    command: ANY
    networks:
      default:

  minio:
    image: minio/minio:RELEASE.2021-01-08T21-18-21Z
    ports:
      - 9000:9000
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - ./volumes/minio:/data
    command: server --address 0.0.0.0:9000 /data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3