FROM node:18.19.0-alpine as base
RUN apk update &&\
    apk add --no-cache build-base git python3 bash
WORKDIR /src/app
COPY . .
COPY package.json yarn.lock ./
RUN yarn
RUN yarn build

FROM node:18.19.0-alpine as runner
WORKDIR /src/app
RUN rm -rf node_modules
COPY --from=base /src/app/config ./config
COPY --from=base /src/app/next.config.mjs ./next.config.mjs
COPY --from=base /src/app/public ./public
COPY --from=base /src/app/.next ./.next
COPY --from=base /src/app/package.json ./package.json
COPY --from=base /src/app/tsconfig.json ./tsconfig.json
COPY --from=base /src/app/src/backend ./src/backend
COPY --from=base /src/app/config ./config
ENV NODE_ENV production
RUN yarn install --production --frozen-lockfile
RUN yarn add typescript tsconfig-paths cross-env

EXPOSE 3000
CMD ["yarn", "start"]
